name: "Run tests with Shisho"

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v1
      - name: Run Shisho
        uses: flatt-security/shisho-action@main
        with:
          ruleset-path: "./rules"
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./shisho.sarif
